---

"COURSE": "CAU_DRALG_2025"
"ASSIGNMENT": "ASSIGNMENT_01"

"ID": "20240065"
"FILES":
    - "**your-path-to-directory**/cau-dralg-2025/assignment_01/array_utils.py" 
"PROBLEMS": 
    - "PROBLEM_01A"
    - "PROBLEM_01B"
    - "PROBLEM_01C"
    - "PROBLEM_01D"
    - "PROBLEM_01E"

    - "PROBLEM_02A"
    - "PROBLEM_02B"
    - "PROBLEM_02C"
    - "PROBLEM_02D"
    - "PROBLEM_02E"
    
